equirectangular_node:
  ros__parameters:
    cx_offset: 0.0
    cy_offset: 0.0
    crop_size: 1250
    translation: [0.0, -0.006, -0.025]
    rotation_deg: [1.4, -1.2, -0.2]
    gpu: True
    out_width: 1920
    out_height: 960
    front_from_left: false
    front_rotation: 0
    back_rotation: 0